[variables]
NIXPACKS_DOTNET_VERSION = "9.0"

[phases.setup]
nixPkgs = ['...', 'dotnet-sdk_9']

[phases.build]
cmds = [
  'cd backend/ColdEmailAPI',
  'dotnet restore',
  'dotnet publish -c Release -o /app/out'
]

[start]
cmd = 'cd /app/out && dotnet ColdEmailAPI.dll'
